server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbkt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1123

    #热部署配置
  devtools:
    restart:
      enabled: true  #开启热部署
  jpa:
    hibernate:
      ddl-auto: validate

#mybatis配置
mybatis:
  type-aliases-package: com.xdmd.environment.*.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰转换

# 配置pageHelper分页插件的内容
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#简单日志配置
logging:
  level:
    root: INFO
    org.springframework.web: debug
  file: D:\\xdmd_hbkj\\hbkt.log
